"use strict";
"use client";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = SuperAdminDashboardPage;
const link_1 = __importDefault(require("next/link"));
const react_1 = require("react");
const lucide_react_1 = require("lucide-react");
const hooks_1 = require("@/domains/dashboard/hooks");
function SuperAdminDashboardPage() {
    const { data: tenants, isLoading, isError, refetch } = (0, hooks_1.useTenantDirectory)();
    const [searchQuery, setSearchQuery] = (0, react_1.useState)('');
    const [filterPlan, setFilterPlan] = (0, react_1.useState)('ALL');
    const filteredTenants = (0, react_1.useMemo)(() => (tenants ?? []).filter((tenant) => (tenant.name.toLowerCase().includes(searchQuery.toLowerCase()) || tenant.subdomain.toLowerCase().includes(searchQuery.toLowerCase())) && (filterPlan === 'ALL' || tenant.plan === filterPlan)), [filterPlan, searchQuery, tenants]);
    const activeTenants = tenants?.filter((tenant) => tenant.status === 'Active').length ?? 0;
    const totalBranches = tenants?.reduce((sum, tenant) => sum + tenant.branches, 0) ?? 0;
    const planBreakdown = (plan) => tenants?.filter((tenant) => tenant.plan === plan).length ?? 0;
    return <div className="space-y-6"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><h1 className="text-2xl font-bold tracking-tight text-white">Platform Tenant Overview</h1><p className="text-xs text-slate-400 mt-0.5">Live provisioned tenant directory and plan distribution.</p></div><link_1.default href="/super-admin/tenants" className="rounded-lg bg-purple-600 px-4 py-2 text-xs font-medium text-white hover:bg-purple-500">Manage tenants</link_1.default></div>
    {isError ? <div className="rounded-xl border border-rose-500/20 bg-rose-500/5 p-4 text-xs text-rose-400 flex items-center justify-between"><span>Unable to load the tenant directory.</span><button onClick={() => refetch()} className="font-medium hover:underline">Retry</button></div> : <><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4"><Metric label="Total tenants" value={isLoading ? 'Loading…' : String(tenants?.length ?? 0)} icon={lucide_react_1.Building}/><Metric label="Active tenants" value={isLoading ? 'Loading…' : String(activeTenants)} icon={lucide_react_1.CheckCircle2}/><Metric label="Total branches" value={isLoading ? 'Loading…' : String(totalBranches)} icon={lucide_react_1.GitBranch}/><div className="rounded-xl border border-slate-800 bg-slate-900/60 p-5"><div className="text-xs text-slate-400">Plan breakdown</div><div className="mt-3 text-sm font-medium text-white">Starter {planBreakdown('Starter')} · Growth {planBreakdown('Growth')} · ERP {planBreakdown('ERP')}</div></div></div>
      <div className="rounded-xl border border-slate-800 bg-slate-900/60 p-6 space-y-4"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><h2 className="font-bold text-sm text-white">Provisioned Tenants Directory</h2><div className="flex items-center gap-3 text-xs"><div className="flex items-center rounded-lg border border-slate-800 bg-slate-950 px-3 py-1.5 w-64"><lucide_react_1.Search className="w-3.5 h-3.5 text-slate-400 mr-2 shrink-0"/><input placeholder="Search clinic name or subdomain..." value={searchQuery} onChange={(event) => setSearchQuery(event.target.value)} className="w-full bg-transparent text-white focus:outline-none"/></div><select value={filterPlan} onChange={(event) => setFilterPlan(event.target.value)} className="rounded-lg border border-slate-800 bg-slate-950 px-3 py-1.5 text-slate-300 focus:outline-none"><option value="ALL">All plans</option><option value="Starter">Starter</option><option value="Growth">Growth</option><option value="ERP">ERP</option></select></div></div>
      {isLoading ? <p className="text-xs text-slate-400">Loading tenant directory…</p> : filteredTenants.length === 0 ? <p className="rounded-lg border border-dashed border-slate-700 p-6 text-center text-xs text-slate-400">No tenants match the current filters.</p> : <div className="space-y-3">{filteredTenants.map((tenant) => <div key={tenant.id} className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 p-3.5 rounded-lg border border-slate-800 bg-slate-900/40 text-xs"><div><div className="font-bold text-white text-sm">{tenant.name}</div><div className="font-mono text-[11px] text-purple-400">{tenant.subdomain}</div></div><div className="text-slate-300">{tenant.plan} · {tenant.branches} branches</div><span className={tenant.status === 'Active' ? 'text-emerald-400' : 'text-rose-400'}>{tenant.status}</span></div>)}</div>}</div></>}</div>;
}
function Metric({ label, value, icon: Icon }) { return <div className="rounded-xl border border-slate-800 bg-slate-900/60 p-5 space-y-2"><div className="flex items-center justify-between text-xs text-slate-400"><span>{label}</span><Icon className="w-4 h-4 text-purple-400"/></div><div className="text-2xl font-bold text-white">{value}</div></div>; }
