import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { AiProviderInterface, AiMessage, AiCompletionOptions } from './ai.interface';
import OpenAI from 'openai';

@Injectable()
export class AiService implements AiProviderInterface {
  private readonly logger = new Logger(AiService.name);
  private readonly openai: OpenAI;
  private readonly defaultModel: string;

  constructor(private readonly configService: ConfigService) {
    const apiKey = this.configService.get<string>('OPENAI_API_KEY') || 'mock-api-key';
    this.defaultModel = this.configService.get<string>('AI_MODEL') || 'gpt-4o-mini';

    this.openai = new OpenAI({
      apiKey,
    });
  }

  async generateCompletion(messages: AiMessage[], options?: AiCompletionOptions): Promise<string> {
    try {
      this.logger.log(`Generating AI completion with ${messages.length} messages`);

      if (this.openai.apiKey === 'mock-api-key') {
        this.logger.debug('Using mock OpenAI response due to mock-api-key');
        return 'This is a mock AI generated summary. In a real environment, this would be generated by OpenAI based on the provided prompt and patient context.';
      }

      const response = await this.openai.chat.completions.create({
        model: options?.model || this.defaultModel,
        messages: messages.map(m => ({
          role: m.role,
          content: m.content,
        })),
        temperature: options?.temperature ?? 0.3,
        max_tokens: options?.maxTokens,
      });

      return response.choices[0]?.message?.content || '';
    } catch (error) {
      this.logger.error('Failed to generate AI completion', error);
      throw new Error('AI Generation failed');
    }
  }
}
